import type { Metadata } from 'next';
import { inter } from '@/app/ui/fonts';
import './globals.css';
import AuthProvider from './context/AuthProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko'>
      <AuthProvider>
        <body className={`${inter.className} antialiased`}>{children}</body>
      </AuthProvider>
    </html>
  );
}
